name: GitHub_API_Tokens
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "This is a comment from the GitHub API token workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
