name: val_and_secrets
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.TEST_SECRET }}
      TEST: ${{ vars.TEST }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${TEST}"