name: val_and_secrets
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.TEST_SECRET }}
      TEST: ${{ vars.TEST }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
      - run: echo "${TEST}"
      - run: echo "SECRETS:${PASSWORD}"
      - run: echo "VARS:${TEST}"